<?php

namespace App\Models;

use App\Scopes\BannedScope;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use SoftDeletes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new BannedScope());
    }

    public function articles()
    {
        return $this->belongsToMany(Article::class)->withTimestamps();
    }

    public function resources()
    {
        return $this->belongsToMany(Resource::class)->withTimestamps();
    }
}
